name: PlayerVanish
version: ${project.version}
main: nl.danieljunek17.playervanish.PlayerVanish
api-version: 1.16
authors: [Danieljnuek17]
description: een plugin voor spelers te verbergen

commands:
  vanish:
    description: hiermee bekom je onzichtbaar
    aliases: [v]